server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /smartacom-ms
spring:
  application:
    name: smartacom-ms
  main:
    banner-mode: "off"
  sleuth:
    sampler:
      probability: 1.0
    log:
      slf4j:
        whitelisted-mdc-keys: principal
        enabled: true
    baggage-keys: principal
  datasource:
    url: ${DB_URL:jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11432074}
    username: ${DB_USERNAME:sql11432074}
    password: ${DB_PASSWORD:ycSakjZr3j}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # generate-ddl: true
    database: default
    open-in-view: false
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:false}
    change-log: classpath:/liquibase/changelog-master.xml
    drop-first: false
    default-schema: ${DB_SCHEMA:sql11432074}
    database-change-log-table: MS_SMARTACOM_DBCHANGELOG
    database-change-log-lock-table: MS_SMARTACOM_DBCHANGELOGLOCK
caching:
  enabled: true
  maxItem: 1000
  expireTime: 12 # in hours

management:
  port: ${MANAGEMENT_SERVER_PORT:8081}
  add-application-context-header: false
  security:
    # Disable security on the management port (NOT FOR PRODUCTION)
    enabled: false


